# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec — REIS AI Windows uygulaması."""
from pathlib import Path

block_cipher = None
ROOT = Path(SPECPATH).resolve()

hidden = [
    "core",
    "core.agent",
    "core.agent.loop",
    "core.evolution",
    "core.evolution.boot",
    "core.evolution.loop",
    "core.evolution.intents",
    "core.evolution.self_diagnostics",
    "core.evolution.self_healing",
    "core.evolution.self_evolver",
    "core.evolution.self_feature_builder",
    "core.evolution.self_optimizer",
    "core.evolution.self_reviewer",
    "core.evolution.self_tester",
    "core.evolution.self_benchmark",
    "core.evolution.web_research",
    "core.evolution.knowledge",
    "core.evolution.dependency_manager",
    "core.evolution.security_auditor",
    "core.evolution.project_mapper",
    "core.evolution.task_state",
    "core.evolution.safe_auto_update",
    "core.evolution.auto_patcher",
    "core.evolution.scan_util",
    "core.model_router",
    "core.model_router.router",
    "core.intent",
    "core.intent.engine",
    "core.context",
    "core.context.engine",
    "core.task_manager",
    "core.task_manager.manager",
    "core.llm_client",
    "core.executor",
    "core.memory",
    "core.metrics",
    "core.security",
    "core.commands",
    "core.env_check",
    "core.logutil",
    "core.turkish",
    "core.planner",
    "core.coder",
    "core.tester",
    "core.debugger",
    "core.recovery",
    "core.scaffold",
    "core.cache",
    "core.backup",
    "core.telegram_bot",
    "core.voice",
    "database",
    "database.store",
    "tools",
    "tools.filesystem",
    "tools.terminal",
    "tools.web_tool",
    "tools.git_tool",
    "tools.project_tool",
    "tools.python_tool",
    "tools.browser_tool",
    "tools.vision_tool",
    "tools.computer_tool",
    "tools.document_tool",
    "tools.desktop_organizer",
    "plugins",
    "plugins.loader",
    "plugins.telegram",
    "ui",
    "ui.app_server",
    "telegram_bot",
    "dotenv",
    "requests",
    "bs4",
    "lxml",
    "colorama",
    "rich",
]

datas = [
    (str(ROOT / "ui" / "web"), "ui/web"),
    (str(ROOT / "config.py"), "."),
    (str(ROOT / ".env.example"), "."),
]

a = Analysis(
    [str(ROOT / "reis_app.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[".venv", "workspace", "tests", "backups", "logs"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="REIS_AI",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="REIS_AI",
)
