"""Safe auto-patches derived from diagnostics (SAFE/CAUTION only, always tested)."""
from __future__ import annotations

import ast
from pathlib import Path
from typing import Any

import config
from core.evolution.safe_auto_update import UpdateLevel, classify_update
from core.evolution.self_evolver import SelfEvolver
from core.evolution.self_tester import SelfTester


class AutoPatcher:
    """Applies only low-risk automated fixes with evolver backup/test/rollback."""

    def __init__(self, evolver: SelfEvolver | None = None, tester: SelfTester | None = None):
        self.evolver = evolver or SelfEvolver()
        self.tester = tester or SelfTester()

    def from_diagnostics(self, diag: dict[str, Any], max_patches: int = 3) -> dict[str, Any]:
        applied: list[dict[str, Any]] = []
        skipped: list[dict[str, Any]] = []

        # 1) Generate missing smoke tests for evolution modules
        for gap in (diag.get("test_gaps") or [])[:max_patches]:
            if "core/evolution/" not in str(gap).replace("\\", "/"):
                continue
            rel = str(gap).replace("\\", "/")
            stem = Path(rel).stem
            dest = config.BASE_DIR / "tests" / f"test_{stem}_smoke.py"
            if dest.exists():
                skipped.append({"kind": "test_gap", "file": rel, "reason": "exists"})
                continue
            mod = rel.replace("/", ".").removesuffix(".py")
            content = (
                f'# auto-generated by AutoPatcher\n'
                f'import sys\nfrom pathlib import Path\n'
                f'sys.path.insert(0, str(Path(__file__).resolve().parent.parent))\n'
                f'import importlib\n'
                f'm = importlib.import_module({mod!r})\n'
                f'print("SMOKE_OK", m.__name__)\n'
            )
            dest.write_text(content, encoding="utf-8")
            tr = self.tester.run_pytest_or_script(dest)
            if tr.get("ok"):
                applied.append({"kind": "test_gap", "file": str(dest), "ok": True})
            else:
                dest.unlink(missing_ok=True)
                skipped.append({"kind": "test_gap", "file": rel, "reason": tr.get("stderr", "")[:200]})

        # 2) Remove unused imports in core/evolution only (SAFE zone)
        unused = [p for p in (diag.get("problems") or []) if p.get("kind") == "unused_import"]
        for item in unused:
            if len(applied) >= max_patches:
                break
            rel = str(item.get("file") or "").replace("\\", "/")
            name = item.get("detail")
            if not rel.startswith("core/evolution/") or not name:
                continue
            path = config.BASE_DIR / rel
            if not path.exists():
                continue
            new_src = _strip_unused_import(path.read_text(encoding="utf-8"), name)
            if new_src is None:
                skipped.append({"kind": "unused_import", "file": rel, "name": name, "reason": "no_change"})
                continue
            level = classify_update(path, new_src)
            if level == UpdateLevel.DANGEROUS:
                skipped.append({"kind": "unused_import", "file": rel, "reason": "dangerous"})
                continue
            r = self.evolver.apply_change(path, new_src, reason=f"strip unused import {name}")
            if r.get("ok"):
                applied.append({"kind": "unused_import", "file": rel, "name": name, "ok": True})
            else:
                skipped.append({"kind": "unused_import", "file": rel, "name": name, "reason": r.get("status")})

        return {"ok": True, "applied": applied, "skipped": skipped, "count": len(applied)}


def _strip_unused_import(source: str, name: str) -> str | None:
    if name in {"annotations", "__future__", "TYPE_CHECKING"}:
        return None
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None
    # never remove symbols exported via __all__
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == "__all__" and isinstance(node.value, (ast.List, ast.Tuple)):
                    for elt in node.value.elts:
                        if isinstance(elt, ast.Constant) and elt.value == name:
                            return None
    lines = source.splitlines(keepends=True)
    drop: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        if isinstance(node, ast.Import):
            keep = [a for a in node.names if (a.asname or a.name.split(".")[0]) != name]
            if len(keep) == len(node.names):
                continue
            if not keep or len(node.names) == 1:
                drop.add(node.lineno - 1)
        elif isinstance(node, ast.ImportFrom):
            keep = [a for a in node.names if (a.asname or a.name) != name]
            if len(keep) == len(node.names):
                continue
            if not keep or len(node.names) == 1:
                drop.add(node.lineno - 1)
    if not drop:
        return None
    out = [ln for i, ln in enumerate(lines) if i not in drop]
    text = "".join(out)
    try:
        ast.parse(text)
    except SyntaxError:
        return None
    return text if text != source else None
